.\"
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.\" Copyright (c) 2020 Kyle Evans <kevans@FreeBSD.org>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd May 9, 2020
.Dt QUICKJAIL 1
.Os
.Sh NAME
.Nm quickjail
.Nd Utility to spawn transient single-command jails
.Sh SYNOPSIS
.Nm
.Oo param Ns = Ns Ar value ... Oc
.Ar command Ns = Ns Ar command ...
.Sh DESCRIPTION
The
.Nm
command is used to create transient single-command jails in a reasonably secure
manner.
.Pp
The key advantage to
.Nm
over
.Xr jail 8
is the model that
.Nm
uses to execute
.Ar command .
.Nm
will fork and execute
.Ar command
in a non-persistent jail, while
.Xr jail 8
will mark the jail as persistent and remove the jail when the child process is
gone.
For some use-cases, this behavior is not ideal as it may potentially leave the
jail behind depending on how the child command exits.
.Sh EXAMPLES
.Nm
.Ar path=/mnt
.Ar command=/bin/sh
.Pp
.Nm
.Ar name=qemu0
.Ar path=/mnt
.Ar command=/bin/sh
.Sh SEE ALSO
.Xr jail 8
.Sh HISTORY
.Nm
was a quick-and-dirty hack to facilitate the author's testing of qemu usermode
emulation.
.Sh AUTHORS
.Nm
was written by
.An Kyle Evans Aq Mt kevans@FreeBSD.org .
